export enum FiltersControllerIds {
    LPF_INPUT,
    LPF_DRIVE,
    LPF_RESONANCE,
    LPF_CUTOFF,
    LPF_FM_AMT,
    LPF_ENV_AMT,
    LPF_LFO_AMT,
    LPF_KBD_AMT,

    SVF_INPUT,
    SVF_DRIVE,
    SVF_RESONANCE,
    SVF_CUTOFF,
    SVF_FM_AMT,
    SVF_ENV_AMT,
    SVF_LFO_AMT,
    SVF_KBD_AMT,

    LPF_EXT_CV,
    LPF_WHEEL,
    LPF_SLOPE,

    FILTERS_LINK_CUTOFF,
    FILTERS_ROUTING,

    SVF_EXT_CV,
    SVF_WHEEL,
    SVF_SLOPE,
}