export enum FxControllerIds {
    DISTORTION_DRIVE,
    DISTORTION_LEVEL,
    DISTORTION_IN,
    DISTORTION_CLIP,
    DISTORTION_OUT,
    BIT_CRUSHER_BITS,
    BIT_CRUSHER_RATE,
    BIT_CRUSHER_LEVEL,
    BIT_CRUSHER_IN,
    BIT_CRUSHER_OUT,
}