export enum CommonFxControllerIds {
    DSP1_PARAM1,
    DSP1_PARAM2,
    DSP1_PARAM3,
    DSP1_EFFECT,
    DSP1_SOURCE,

    DSP2_PARAM1,
    DSP2_PARAM2,
    DSP2_PARAM3,
    DSP2_EFFECT,
    DSP2_SOURCE,
    DSP2_CHAIN,

    CHORUS_RATE,
    CHORUS_DEPTH,
    CHORUS_SOURCE,
    CHORUS_MODE,

    BIT_CRUSHER_BITS,
    BIT_CRUSHER_RATE,
    BIT_CRUSHER_SOURCE,

    LEVEL_DSP1,
    LEVEL_DSP2,
    LEVEL_CHORUS,
    LEVEL_BIT_CRUSHER,
}