// GENERATED FILE, DO NOT EDIT
// shared ids for RPC commands
export enum FunctionNames {
  setCvStart = 0,
  setCvEnd = 1,
  setCvCurve = 2,
  setCvParams = 3,
  saveCvMapping = 4,
  saveCvMappings = 5,
  loadCvMapping = 6,
  loadCvMappings = 7,
  setTrimmerSetting = 8,
  saveTrimmerSettings = 9,
  setCVOverride = 10,
  releaseCVOverride = 11,
  releaseCVOverrides = 12,
  toggleSvfInSummedToCalibrateMix = 13,
  tuneVco = 14,
  calibrateDCO1 = 15,
  calibrateDCO2 = 16,
  measureVcoOctaves = 17,
  measureVcoAll = 18,
  manualTuneVcoStart = 19,
  manualTuneVcoStop = 20,
  powerDown = 21,
  powerUp = 22,
  dacStopUpdates = 23,
  dacStartUpdates = 24,
  unisonDetuneFactor = 25,
  setCtrlAllParams = 26,
  setCtrlAllNonModSettings = 27,
  setCtrlAllEnvParams = 28,
  setCtrlAllEnvSettings = 29,
  setCtrlAllEnvStageSettings = 30,
  setCtrlAllLfoParams = 31,
  setCtrlAllLfoSettings = 32,
  setCtrlAllLfoStageSettings = 33,
  setAllModAmounts = 34,
  setAllEnvModAmounts = 35,
  setAllLfoModAmounts = 36,
  changeMidiSpeed = 37,
  toggleVoicePower = 38,
  voiceDacStopUpdates = 39,
  voiceDacStartUpdates = 40
}
