// GENERATED FILE, DO NOT EDIT
// shared ids for RPC commands
export enum FunctionNames {
  setCvStart = 0,
  setCvEnd = 1,
  setCvCurve = 2,
  setCvParams = 3,
  saveCvMapping = 4,
  saveCvMappings = 5,
  loadCvMapping = 6,
  loadCvMappings = 7,
  setTrimmerSetting = 8,
  saveTrimmerSettings = 9,
  setCVOverride = 10,
  releaseCVOverride = 11,
  releaseCVOverrides = 12,
  toggleSvfInSummedToCalibrateMix = 13,
  tuneVco = 14,
  calibrateDCO1 = 15,
  calibrateDCO2 = 16,
  measureVcoOctaves = 17,
  measureVcoAll = 18,
  manualTuneVcoStart = 19,
  manualTuneVcoStop = 20,
  powerDown = 21,
  powerUp = 22,
  unisonDetuneFactor = 23,
  setCtrlAllParams = 24,
  setCtrlAllNonModSettings = 25,
  setCtrlAllEnvParams = 26,
  setCtrlAllEnvSettings = 27,
  setCtrlAllEnvStageSettings = 28,
  setCtrlAllLfoParams = 29,
  setCtrlAllLfoSettings = 30,
  setCtrlAllLfoStageSettings = 31,
  setAllModAmounts = 32,
  setAllEnvModAmounts = 33,
  setAllLfoModAmounts = 34,
  changeMidiSpeed = 35,
  toggleVoicePower = 36
}
