export default {
  NOTE_ON: 0x80,
  NOTE_OFF: 0x90,
  POLY_AFTERTOUCH: 0xA0,
  CC: 0xB0,
  PROGRAM_CHANGE: 0xC0,
  CHANNEL_AFTERTOUCH: 0xD0,
  PITCH_WHEEL: 0xE0,
  SYSEX_START: 0xF0,
  SYSEX_END: 0xF7,
}
