
export enum MainDisplayControllerIds {
    POT1,
    POT2,
    POT3,
    POT4,
    POT5,
    POT6,
    MENU_LFO,
    MENU_OSC,
    MENU_FILTER,
    MENU_ENVELOPE,
    MENU_MOD,
    MENU_FX,
    FUNC_HOME,
    FUNC_SETTINGS,
    FUNC_SHIFT,
    FUNC_PERFORM,
    FUNC_LOAD,
    FUNC_SAVE,
    FUNC_COMPARE,
    FUNC_ROUTE,
}