import oscApi from './oscApi'
import { ApiSource } from '../../types'

export enum OscControllerIds {
    DCO1_NOTE,
    DCO1_WAVEFORM,
    DCO1_SUB1,
    DCO1_SUB2,
    DCO1_PW,
    DCO1_SYNC,
    DCO1_MODE,
    DCO1_SUB_WAVE,
    DCO1_WHEEL,
    DCO1_LFO,
    DCO1_KBD,

    DCO2_NOTE,
    DCO2_DETUNE,
    DCO2_WAVEFORM,
    DCO2_SUB1,
    DCO2_SUB2,
    DCO2_PW,
    DCO2_MODE,
    DCO2_SUB_WAVE,
    DCO2_WHEEL,
    DCO2_LFO,
    DCO2_KBD,

    VCO_NOTE,
    VCO_DETUNE,
    VCO_WAVEFORM,
    VCO_CROSSMOD,
    VCO_PW,
    VCO_SYNC,
    VCO_CROSSMOD_SRC,
    VCO_EXT_CV,
    VCO_WHEEL,
    VCO_LFO,
    VCO_KBD,
}