export { isFontAwesomeEnabled } from './is-font-awesome-enabled'
export { relativeTimeWindows } from './relative-time-windows'
export { floatPrecision } from './float-precision'
export { fileSize } from './file-size'
export { move } from './move'
